name: Build and Test
on:
  push:
    tags:
      - "*"
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  pytest:
    if: always()
    name: Ex1 ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0} # needed for conda env to click
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: imagetocsv
          environment-file: environment.yml
          auto-activate-base: false
      # Needed for python 3.7 only
      - name: Install dependencies (linux)
        if: runner.os == 'Linux'
        run: conda install -y gcc gxx
      - name: Install dependencies (macos)
        if: runner.os == 'macos'
        run: conda install -y clangxx_osx-64
      - name: Install dependencies
        run: pip install --no-cache-dir ".[dev]"  # opencv known for cache issues
      - name: Unit Testing
        run: pytest -xsvv tests/test_imagetocsv.py
