name: Build and Test
on:
  push:
    tags:
      - "*"
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  pytest:
    name: Ex1 ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0} # needed for conda env to click
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.8, 3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: imagetocsv
          environment-file: environment.yml
          auto-activate-base: false
      # Needed for python 3.7 only
      - name: Install dependencies (linux)
        if: runner.os == 'Linux'
        run: sudo apt install --yes libpoppler-cpp-dev pkg-config tesseract-ocr libtesseract-dev
      - name: Install dependencies
        run: |
          pip install '.[dev]'
      - name: Unit Testing
        run: pytest -xsvv tests/test_imagetocsv.py
