name: Build and Test
on:
  push:
    tags:
      - "*"
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  pytest:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7] # , 3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: anaconda-client-env
          environment-file: environment.yml
      - name: Install dependencies
        run: |
          python -m pip install .
      - name: Unit Testing
        run: pytest -xsv tests/test_imagetocsv.py
