name: Build and Test
on:
  push:
    tags:
      - "*"
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7] # , 3.8, 3.9, "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (linux)
        if: runner.os == 'Linux'
        run: sudo apt install --yes build-essential libpoppler-dev pkg-config libtesseract-dev libgl1
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install pkg-config poppler tesseract
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install poppler tesseract
      - name: Install Python Dependencies
        run: pip install '.[dev]'
      - name: Unit Testing
        run: pytest -xsv tests/test_imagetocsv.py
