name: Build and Test
on:
  push:
    tags:
      - "*"
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  pytest:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.7] # , 3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
      - name: Install dependencies (linux)
        if: runner.os == 'Linux'
        run: sudo apt install --yes build-essential
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install '.[dev]'
      - name: Unit Testing
        shell: bash -l {0}
        run: pytest -xsv tests/test_imagetocsv.py
